name: Build and deploy reverse proxy
on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    env:
      container_name: ssi-proxy

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Log in to GitHub container registry
        run: ssh server 'docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_PAT }}'

      - name: remove previous image
        run: |
          ssh server 'docker images | grep ${{ env.REPO }} | tr -s \' \' | cut -d \' \' -f 2 | xargs -I {} docker rmi \
          ghcr.io/${{ env.REPO }}:{}'
        continue-on-error: true

      - name: Pull image
        run: ssh server 'docker pull ghcr.io/${{ env.REPO }}:${{ github.sha }}'

      - name: Stop and delete previous container
        run: ssh server 'docker stop ${{ env.container_name }} && docker rm ${{ env.container_name }}'
        continue-on-error: true

      - name: Run image
        run: |
          ssh server '\
          docker run -d \
              --restart=always \
              -e VIRTUAL_HOST=${{ secrets.SSI_DOMAIN }} \
              -e LETSENCRYPT_HOST=${{ secrets.SSI_DOMAIN }} \
              --network=${{ secrets.DOCKER_NETWORK }} \
              --name ${{ env.container_name }} \
              ghcr.io/${{ env.REPO }}:${{ github.sha }} \
          '
